### ISSUE TITLE
Pretrained SPADE on CAOS

### ISSUE THREAD

**Issue by DarioFontanel** [YingdaXia/SynthCP#1]
Hi @YingdaXia,

I could not find the pretrained weights of Spade for Anomaly Segmentation on CAOS benchmark. Could you please share them?

Thank you

**Comment by YingdaXia** [comment]
Hi DarioFontanel,

The pretrained weight is in ```checkpoints/caos/```.  Please copy it to ```spade-caos/checkpoints/caos``` before use them. If other issues come out, please contact us.

Thanks,
Yingda

**Comment by DarioFontanel** [comment]
Found it, thank you.
